### ISSUE TITLE
GO2 is crawling in Gazebo &  talker-listener program

### ISSUE THREAD

**Issue by XT-william** [arjun-sadananda/go2_nav2_ros2#2]
Hi, thank you for sharing the code!

I followed your project to the step "Run: Go2 navigates 2 goal", and I got the same result as in your README, but I noticed that in Gazebo, the dog's posture is lying down, which means that the GO2 is crawling instead of walking. I want to know if I can make the dog stand up and walk.

In addition, if I want to connect with my real GO2 I may need a talker-listener program. Is there such a program in the project?

Thanks for sharing this code, it helps me a lot.

**Comment by arjun-sadananda** [comment]
Hi @xutianzhuo,

I'm glad it was useful for you!

So in the gait.yaml file, the nominal_height parameter needs to be changed to around .25.

I also later discovered that the odom_scaler parameter can be used instead of the modifications I made to the line 189, 190 of state_estimation.cpp (needs to be reverted back to without the 2x multiplier, Since seeing odom_scalar to 2 or actually 1.8 would do the same).

I also later discovered that depending on the computer (say RTF of .5 vs a RTF of 1) the robot behaves differently and therefore needs some more parameter (like Odom_scaler and stance_duration) changes in the gait.yaml file to tackle those issues.

(If it is working fine for you then nevermind that, else i shall elaborate further, and probably update the repo and readme accordingly)


About the hardware interfacing i haven't looked into it yet, therefore would be able to give the best answer. But i think you should look at the ROS2 repo of the oficial unitree go2 repos. I believe they have explained the hardware interfacing in that repo. 

Regards
Arjun
